<a href="https://colab.research.google.com/github/JIMINlx/BU-7300-Data-Analytics-and-Programming/blob/main/7300_numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Creating Arrays:
attributes like shape, size, ndim, dtype, and itemsize.

In [2]:
import numpy as np

a_list = [1,2,3,4,5]
a = np.array(a_list)
print(a)

print(a.shape)             #尺寸数量，5->5列，因为是1维数组，所以是（5,）

print('---------------------------------')

# ndim is for number of dimensions
print(a.ndim)              #返回数组的维度

print('---------------------------------')

# size is for number of elements
print(a.size)

print('---------------------------------')

# dtype is for data type, int 2^5
print(a.dtype)

print('---------------------------------')

# itemsize is for size of each element,数组中每个元素的大小，以字节为单位。float64 占用 64 个 bits，每个字节长度为 8，所以 64/8，占用 8 个字节
print(a.itemsize)
print('\n')

b_list = [[1,2,3],[4,5,6]]
print(b_list[0][2])                #矩阵,第一行第3个数

print('---------------------------------')

b = np.array(b_list)
print(b)
print('---------------------------------')

print(b.shape)                   #2行3列
print('---------------------------------')

print(b.ndim)                   #2维数组
print('---------------------------------')

print('b_size:',b.size)              #6个元素
print('\n')

# astype is not in-place operation
b = b.astype(np.float16)
print(b.dtype)
print(b.itemsize)
print('\n')

[1,2,3,4],[5,6,7,8]#
c = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])#Tensor张量
c = c.astype(np.float32)
print(c[1][1][1])#print out '14'
print(c)
print(c[0][1][2])#print out '7'
print(c.shape)#查看矩阵或数组的维数
print(c.ndim)
print(c.size)
print(c.dtype)
print(c.itemsize)
print('\n')



[1 2 3 4 5]
(5,)
---------------------------------
1
---------------------------------
5
---------------------------------
int64
---------------------------------
8


3
---------------------------------
[[1 2 3]
 [4 5 6]]
---------------------------------
(2, 3)
---------------------------------
2
---------------------------------
b_size: 6


float16
2


14.0
[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]
7.0
(2, 2, 4)
3
16
float32
4




#### numpy array initialization
np.zeros(), np.ones(), np.arange(), np.linspace()

In [ ]:
a = np.zeros((2,3))
print(a)

a = np.ones((2,3))
print(a)

# the following will generate numbers between 0 and 10, which is two numbers apart
a = np.arange(0,10,2)
print(a)

# the following will generate 6 numbers between 0 and 10, no matter what the step is
a = np.linspace(0,10,6)#生成等差数列
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[ 0.  2.  4.  6.  8. 10.]


### Basic Operations:
Element-wise operations, broadcasting, and universal functions (ufuncs).

Arithmetic Operations: Addition, subtraction, multiplication, division, and power.

Statistical Operations: Mean, median, standard deviation, variance, min, max, sum, and product.

In [ ]:
a_array = np.array([1,2,3])
b_array = np.array([4,5,6])
a_list=[1,2,3]
b_list=[4,5,6]
print(a_list+b_list)#数组相加，print out‘[1,2,3][4,5,6]'

print(a_array + b_array)#数组之间的数相加'[5,7,9]'
print(a_array - b_array)
print(a_array * b_array)
print(a_array / b_array)

#broadcasting
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a + 100)
print(a * 100)
# power
print(a ** 2)#square,pow(a,2)->a^2

# statistical functions, they do not require axis
print(a.mean())
print(a.std())
print(a.var())
print(a.sum())
print(a.max())
print(a.min())
print(a.argmax())
print(a.argmin())#使目标函数f(x)取最小值时的索引

# universal functions
print(np.sqrt(a))
print(np.exp(a))
print(np.power(a,2))


### Indexing and Slicing

Basic Indexing: Accessing array elements using indices.
基本索引:使用索引访问数组元素。
Slicing: Extracting subarrays using slice notation.
切片:使用切片表示法提取子数组。

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #n.array数组
print(a)
# first row, second column
print(a[0,1])
# second row, first column
print(a[1,0])
print('-----------------------------------------')

# slicing, this will return the first row
print(a[0])#print out the first row
# this will return the first row as well
print(a[0,:])
# this will return the first column
print(a[:,0])
print(a[0,1:3])#只输出两个数
print(a[0,1:])
print('a[0,:2] = ',a[0,:2])
# this will return the first two rows, and the last three columns
print(a[:2,1:])
print(a[0,1:])
print(a[0,-1])
print(a[-1,0])
print(a[a.shape[0]-1])
print(a[a.shape[0]-1,0])#a.shape[0]->第一行，a.shape[0]-1，指最后一行
print(a[-1,-1])
print(a[-1,:-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
5
-----------------------------------------
[1 2 3 4]
[1 2 3 4]
[1 5 9]
[2 3]
[2 3 4]
a[0,:2] =  [1 2]
[[2 3 4]
 [6 7 8]]
[2 3 4]
4
9
[ 9 10 11 12]
9
12
[ 9 10 11]


### Boolean Indexing

Using boolean arrays to select elements.

In [ ]:

a = np.array([[1,2,3,4 ],[5,6,7,8],[9,10,11,12]])
print(a)
#this is just a broadcast operation and results a new array of the same shape containing boolen
print(a>5)#boolen
print(a[a>5])#true-return,false不return
print(a[a%2==0])
# needto know that logic operators are different in numpy compare with normal python
print(a[(a>2) & (a<11)])#注意用逻辑符号，list 用and，or……
print(a[(a<6) | (a>11)])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]
[ 3  4  5  6  7  8  9 10]
[ 1  2  3  4  5 12]


### numpy array manipulation
repeat an array of (with axis) for: Mean, median, standard deviation, variance, min, max, sum

In [ ]:
a = np.array([[1,2,3],[4,5,6]])


print(a)
print(a.mean(axis=0))#数组中第一列的平均数
print(a.mean(axis=1))
print(a.std(axis=0))
print(a.std(axis=1))
print(a.var(axis=0))
print(a.var(axis=1))
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.max(axis=0))
print(a.max(axis=1))
print(a.min(axis=0))
print(a.min(axis=1))
print(a.argmax(axis=0))
print(a.argmax(axis=1))
print(a.argmin(axis=0))
print(a.argmin(axis=1))

[[1 2 3]
 [4 5 6]]
[2.5 3.5 4.5]
[2. 5.]
[1.5 1.5 1.5]
[0.81649658 0.81649658]
[2.25 2.25 2.25]
[0.66666667 0.66666667]
[5 7 9]
[ 6 15]
[4 5 6]
[3 6]
[1 2 3]
[1 4]
[1 1 1]
[2 2]
[0 0 0]
[0 0]


### Array Manipulation
Reshaping Arrays: Using `reshape()`, `ravel()`, and `flatten()`.

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a = a.reshape(3,2)#将2*3矩阵变为3*2矩阵
print(a)
print('---------------')
#reship to 1D using -1,-1 will be calculated automatically
print(a.reshape(-1))#重塑，拉平数据
# ravel will flatten the array to 1D, but it will return a "view" of the array
b = a.ravel()#a是基于b的，所以b变化时a也会变化，拉平数据，2D变1D
print(b)
print(a)
b[0] = 100
print(a)

# flatten will flatten the array to 1D, but it will return a "copy" of the array
a = np.array([[1,2,3],[4,5,6]])
b = a.flatten()
print(b)
b[0] = 100
print(a)

[[1 2]
 [3 4]
 [5 6]]
---------------
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[100   2]
 [  3   4]
 [  5   6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


### Joining Arrays:
Concatenation using `np.concatenate()`, `np.vstack()`, and `np.hstack()`.

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print(np.concatenate((a,b),axis=0))#数组拼接，axis=0->对0轴进行纵向拼接横
print(np.concatenate((a,b),axis=1))
print('\n')
# vstack and hstack are the same as concatenate
print(np.vstack((a,b)))
print(np.hstack((a,b)))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### Splitting Arrays:
Using `np.split()`, `np.hsplit()`, and `np.vsplit()`

In [ ]:
a = np.array([[1,2,3,4],[4,5,6,8]])
print(a)

# split will return a list of numpy arrays
print(np.split(a,2))#将数组均分，一个6*4数组均分成两个3*4数组
# the following are the same as the above
print(np.split(a,2,axis = 0))
# vertical split, which is spliting into list of rows
print(np.vsplit(a,2))

print('\n')
print(np.split(a,4,axis=1))
# horizontal split, which is spliting into list of columns
print(np.hsplit(a,2))
print(type(np.split(a,2)))

# you won't be able to split the array into uneven parts
# print(np.split(a,3))


[[1 2 3 4]
 [4 5 6 8]]
[array([[1, 2, 3, 4]]), array([[4, 5, 6, 8]])]
[array([[1, 2, 3, 4]]), array([[4, 5, 6, 8]])]
[array([[1, 2, 3, 4]]), array([[4, 5, 6, 8]])]


[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]]), array([[4],
       [8]])]
[array([[1, 2],
       [4, 5]]), array([[3, 4],
       [6, 8]])]
<class 'list'>


### Linear Algebra

Matrix Operations: Matrix multiplication, dot product, and inner product



In [3]:
#matrix operations

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)
# element-wise multiplication
print(a*b)
print('\n')

# the following code does the same thing
# matrix multiplication
print(a.dot(b))
# I prefer the following way
print(a@b)
print(a.__matmul__(b))

# the difference is when we apply broadcasting to 3D array
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
b = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])

print(a)
print('\n')
print(b)


# this is to broadcast multiplication of 3D array as set of mulitplication of 2D array
print('a@b:\n',a@b)
print('\n')
# this is identical to the above
for i in range(a.shape[0]):
    print(a[i]@b[i])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
a@b:
 [[[ 22  28]
  [ 49  64]]

 [[220 244]
  [301 334]]]


[[22 28]
 [49 64]]
[[220 244]
 [301 334]]


### Random Number Generation


In [ ]:
# uniform distribution
a = np.random.random((2,3))
print(a)

# normal distribution
a = np.random.randn(2,3)
print(a)

a = np.random.randint(0,10,(2,3))
print(a)

a = np.random.normal(0,1,(2,3))
print(a)

a = np.random.rand(2,3,4)
print(a)

### Decompositions

Eigenvalues, eigenvectors, and singular value decomposition (SVD).

Solving Linear Systems: Using `np.linalg.solve()` and `np.linalg.inv()`.

In [ ]:
a = np.random.randn(3,4)
print(a)

eigVal, eigvect = np.linalg.eig(a @ a.T)
print(eigVal)
print(eigvect)

A = np.random.randn(3,3)
b = np.random.randn(3,1)
x = np.linalg.solve(A,b)

print(A)
print(b)
print(x)

print(A@x)